package/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Enter the content", validators=[DataRequired()])
    submit = SubmitField("Post")

package/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for
from package.models import Post, Like, Comment
from package import db

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    pg = request.args.get("page", 1, type=int)
    val = request.args.get("val", 1 , type=int)
    posts = get_order(val).paginate(per_page=5, page=pg)
    return render_template("home.html", posts=posts, val=val)

@main.route("/home/order", methods=["POST"])
def post_order():
    print("Entered")
    val = int(request.form.get("order"))

    return redirect(url_for("main.home", val=val))

def get_order(val):
    if val==1 or val==0:
        posts = Post.query.order_by(Post.date_posted.desc())
    elif val==2:
        posts = Post.query.order_by(Post.date_posted)
    elif val==3:
        posts = Post.query.outerjoin(Like).group_by(Post.id).order_by(db.func.count(Like.id).desc())
    elif val==4:
        posts = Post.query.outerjoin(Comment).group_by(Post.id).order_by(db.func.count(Comment.id).desc())

    return posts


@main.route("/about")
def about():
    return render_template("about.html", title="Joshua")

package/posts/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user
from package import db
from package.posts.forms import PostForm
from package.models import Post, Like

posts = Blueprint("posts", __name__)



@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post is created", "success")
        return redirect(url_for("main.home"))
    return render_template("create_post.html", title="New Post", form=form)


@posts.route("/post/<int:id>", methods=["GET", "POST"])
def post(id):
    post = Post.query.get_or_404(id)
    like_post = Like.query.filter_by(p_id=id).all()
    return render_template("post.html", title=post.title, post=post, like_post=len(like_post))

@posts.route("/post/<int:id>/like", methods=["POST"])
@login_required
def like_post(id):
    like = Like.query.filter_by(u_id=current_user.id, p_id=id).first()
    # print(Like.query.filter_by(u_id=current_user.id, p_id=id).all())
    if like:
        db.session.delete(like)
        db.session.commit()
    else:
        new_like = Like(u_id=current_user.id, p_id=id)
        db.session.add(new_like)
        db.session.commit()
    return redirect(url_for('posts.post', id=id))



@posts.route("/post/<int:id>/update", methods=["GET", "POST"])
@login_required
def update_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content =  form.content.data 
        db.session.commit()
        flash("Your post is updated", "success")
        return redirect(url_for("posts.post", id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("create_post.html", title="Update Post", form=form)


@posts.route("/post/<int:id>/delete", methods=["POST"])
@login_required
def delete_post(id):
    post = Post.query.get_or_404(id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("Your post is deleted", "success")
    return redirect(url_for("main.home"))

package/users/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import  current_user, login_user, logout_user
from package import db, bcrypt
from package.models import Post, User, Comment, Like
from package.users.forms import RegistrationForm, LoginForm, UpdateForm, RequestResetForm, ResetPasswordForm
from package.users.utils import save_img, send_reset

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password = hashed_pwd)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for("main.home"))
        else:
            flash("Login unsuccessful", "danger")
            
    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@users.route("/account", methods=["GET", "POST"])
def account():
    if current_user.is_authenticated:
        form = UpdateForm()
        if form.validate_on_submit():
            if form.image.data:
                picture_file_name = save_img(form.image.data)
                current_user.image = picture_file_name
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash("Your Account is updated", "success")
            return redirect(url_for("users.account"))
        elif request.method == "GET":
            form.username.data = current_user.username
            form.email.data = current_user.email
        img = url_for("static", filename="profile_pics/" + current_user.image)
        return render_template("account.html", title="Account", image = img, form=form)
    else:
        return redirect("login")
    

@users.route("/user/<string:username>")
def user_post(username):
    pg = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(per_page=3, page=pg)
    comments = Comment.query.filter_by(u_id=user.id).all()
    likes=0
    for post in Post.query.filter_by(author=user).all():
        likes += post.like_count
    return render_template("user_posts.html", posts=posts, user=user, comm = comments, len= len(comments), likes=likes)


@users.route("/request-password", methods=["GET", "POST"])
def request_password():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset(user)
        flash("Email has been sent to your email address", "info")
        return redirect(url_for("users.login"))
    return render_template("request_password.html", form=form, title="Request password")

@users.route("/reset-password/<token>", methods=["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_token(token)
    if user is None:
        flash("Invalid or expired token", "warning")
        return redirect(url_for("users.request_password"))
    else:
        form = ResetPasswordForm()
        if form.validate_on_submit():
            hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
            user.password = hashed_pwd
            db.session.commit()
            flash(f"Your password is updated", "success")
            return redirect(url_for("users.login"))

        return render_template("reset_password.html", form=form, title="Reset password")

package/templates/about.html
{% extends 'layouts.html' %}
{% block content %}
  <h3>About page!</h3>
  <p>This site is developed by Joshua</p>
{% endblock content%}

package/templates/account.html
{% extends 'layouts.html' %}
{% block content %}
  <div class="container-md row d-flex flex-wrap">
    <div class="col d-flex justify-content-center">
      <img src="{{ image }}" class="p-md-3 rounded-pill" style="width: 300px;  height: 300px;"/>
    </div>
    <div class="col">
      <div class="container">
        <div class="row justify-content-start">
          <div class="col-md-8">
            <form method="post" action="" class="px-4 lg mt-4" novalidate enctype="multipart/form-data">
              <h3>{{ current_user.username }}</h3>
              <p class="mb-0">{{ current_user.email }}</p>
              {{ form.hidden_tag() }}
              <fieldset class="d-flex flex-column">
                <center class="fs-2 py-4">Account Info</center>
                <div class="form-group mb-4">
                  {{ form.username.label(class='form-label') }}
                  {% if form.username.errors %}
                    {{ form.username(class='form-control is-invalid') }}
                    <div class="invalid-feedback">
                      {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.username(class='form-control') }}
                  {% endif %}
                </div>
                <div class="form-group mb-4">
                  {{ form.email.label(class='form-label') }}
                  {% if form.email.errors %}
                    {{ form.email(class='form-control is-invalid') }}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class='form-control') }}
                  {% endif %}
                </div>
                <div class="form-group">
                  {{ form.image.label(class='form-label') }}
                  {{ form.image(class='form-control-file') }}
                  {% if form.image.errors %}
                      {% for error in form.image.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                      {% endfor %}

                  {% endif %}
                </div>
              </fieldset>
              <div class="form-group text-center my-3">{{ form.submit(class='btn btn-primary my-3') }}</div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

package/templates/create_comment.html
{% extends 'layouts.html' %}
{% block content %}
  <div class="d-flex flex-column flex-md-row justify-content-center mediumheight" >
    <div class="bg-white text-black overflow-auto-md text-overflow" style="max-width: 450px;">
      <div class="flex-fill mx-3 py-3 ">
        <p class="title fs-4 text-decoration-none text-danger">{{ post.title }}</p>
        <p class="mt-3 over">{{ post.content }}</p>
        <div class="d-flex flex-column" style="">
          <p class="bold fw-5 fs-6">
            Published By
            <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="text-decoration-none mx-1 pt-1 text-info">{{ post.author.username }}</a>
            on
            {{ post.date_posted.strftime('%d %B %Y') }}
          </p>
        </div>
      </div>
      
    </div>
    <div class="d-flex flex-column justify-content-between border border-light text-overflow overflow-auto">
      <div class="px-2" style="max-width: 300px;">
        {% for c in  comment%}
            <p><a class="text-decoration-none" href="{{url_for("users.user_post", username=c.author.username)}}">{{c.author.username}}</a>: {{c.content}}</p>
        {% endfor %}

      </div>
      <form method="post" action="" class="" style="width: 100%;" novalidate>
        {{ form.hidden_tag() }}
        <fieldset class="d-flex flex-column">
          <div class="form-group">
            {% if form.content.errors %}
              <div class="d-flex is-invalid">
                {{ form.content(class='', placeholder='Write your comment here...', style='width:80%') }}
                {{ form.send(class='btn btn-primary', style="width:20%;") }}
                </div>
              <div class="invalid-feedback">
                {% for error in form.content.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
            <div class="d-flex">
                {{ form.content(class='', placeholder='Write your comment here...', style='width:80%') }}
                {{ form.send(class='btn btn-primary',  style="width:20%;") }}
                </div>
            {% endif %}
          </div>
        </fieldset>
      </form>
    </div>
  </div>
{% endblock %}

package/templates/create_post.html
{% extends 'layouts.html' %}
{% block content %}
  <form method="post" action="" class="border border-info mt-3 px-4 lg" novalidate>
    {{ form.hidden_tag() }}
    <fieldset class="d-flex flex-column">
      <center class="fs-2">{{title}}</center>
      <div class="form-group">
        {{ form.title.label(class='form-label') }}
        {% if form.title.errors %}
          {{ form.title(class='form-control is-invalid') }}
          <div class="invalid-feedback">
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.title(class='form-control') }}
        {% endif %}
      </div>
      <div class="form-group">
        {{form.content.label(class='form-label') }}
        {% if form.content.errors %}
          {{ form.content(class='form-control is-invalid') }}
          <div class="invalid-feedback">
            {% for error in form.content.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
          {{ form.content(class=' form-control', rows="6") }}
        {% endif %}
      </div>
    </fieldset>
    <div class="form-group text-center">{{ form.submit(class='btn btn-primary my-3') }}</div>

  </form>
{% endblock %}

package/templates/home.html
{% extends 'layouts.html' %}
{% block content %}
<form method="post" action="{{url_for("main.post_order")}}" class="d-flex justify-content-end mx-3">
  <select name="order" onchange="this.form.submit()" class="">
    <option disabled selected value="0">--Sort By--</option>
    <option value="1">Date posted - Newest</option>
    <option value="2">Date posted - Oldest</option>
    <option value="3">Most likes</option>
    <option value="4">Most comments</option>
  </select>
</form>
  {% for post in posts.items %}
  <div class="bg-light rounded text-black my-4 mx-3">
    <div class="container  d-flex justify-content-center flex-md-row flex-column">
      <div class="d-flex align-items-center justify-content-center">
        <img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + post.author.image) }}" style="width: 100px;  height: 100px;" />
      </div>
      <div class="flex-fill text-center mx-3 py-3">
        <a class="title fs-4 text-decoration-none text-black" href="{{ url_for('posts.post', id=post.id) }}">{{ post.title }}</a>

        <p class="mt-3">{{ post.content }}</p>
      </div>
      <div class="d-flex flex-md-column justify-content-center flex-wrap">
        <p class="bold fw-4 fs-5 m-0">Published By</p>
        <a href="{{url_for("users.user_post", username=post.author.username)}}" class="text-decoration-none mx-1 pt-1">{{ post.author.username }}</a>
        <p class="m-0 pt-1 mx-1">on</p>
        <p class="pt-1 m-0">{{ post.date_posted.strftime('%d %B %Y') }}</p>
      </div>
    </div>
    <div class="d-flex justify-content-around bg-info">
      <form method="post" action="{{url_for("posts.like_post", id=post.id)}}">
        {% if current_user.is_authenticated and post.has_liked(current_user)%}
        <button id="like" type="submit" class="bg-info border-0 text-primary pb-2 d-flex"><p class="pe-2 pt-1 m-0 fw-semibold">Like</p><img src="{{url_for("static", filename="icons/image2.png")}}" class="mt-2 me-1"  style="width: 15px; height: 15px;"></img><p class="pt-1 my-0 fw-semibold"> ({{post.like_count}})</p></button>
        {%  else %}
        <button  id="like" type="submit" class="bg-info border-0 text-primary pb-2 d-flex"><p class="pe-2 pt-1 m-0 fw-semibold">Like</p><img src="{{url_for("static", filename="icons/image.png")}}"  class="mt-2 me-1" style="width: 15px; height: 15px;"></img><p class="pt-1 my-0 fw-semibold"> ({{post.like_count}})</p></button>
        {% endif %}
      </form>
      <a href="{{url_for("comment.new_comment", p_id=post.id)}}" class="text-decoration-none pt-1">Comment 💬</a>
    </div>
  </div>

  {% endfor %}

  <div class="d-flex justify-content-center">
    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page %}
        {% if posts.page == page %}
          <a href="{{ url_for('main.home', page=page, val=val) }}" class="btn btn-info border boder-1 mx-1">{{ page }}</a>
        {% else %}
          <a href="{{ url_for('main.home', page=page, val=val) }}" class="btn btn-light border boder-1 mx-1">{{ page }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}

package/templates/layouts.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
      <title>Blog - {{ title }}</title>
    {% else %}
      <title>Blog</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" />
  </head>
  <body>
    <header>
      <div class="container-fluid p-0 m-0 fw-semibold bg-dark text-light" style="min-height: 100vh;">
        <nav class="navbar navbar-expand-lg bg-primary navbar-dark sticky-top">
          <div class="container-fluid">
            <a class="navbar-brand fs-3 me-4" href="{{ url_for('main.home') }}">Bloger</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse fs-5" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item mw-5">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item mw-3">
                  <a class="nav-link active" href="{{ url_for('main.about') }}">About</a>
                </li>
              </ul>
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="btn nav-item nav-link   active " href="{{ url_for('posts.new_post') }}">New Blog</a>
                  <a class="btn nav-item nav-link mx-3  active " href="{{ url_for('users.account') }}">Account</a>
                  <a class="btn nav-item nav-link mx-3 border border-warning rounded active border-2 text-warning fw-normal" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="btn nav-item nav-link mx-3 border border-warning rounded active border-2 text-warning fw-normal" href="{{ url_for('users.login') }}">Login</a>
                  <a class="btn nav-item nav-link mx-3 border border-warning rounded active border-2 text-warning fw-normal" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
        <div class="mt-3 mx-2">
          {% with message=get_flashed_messages(with_categories=true) %}
            {% if message %}
              {% for category, msg in message %}
                <div class="alert alert-{{ category }}">{{ msg }}</div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          {% block content %}

          {% endblock %}
        </div>
      </div>
    </header>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

package/templates/login.html
{% extends 'layouts.html' %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post" action="" class="border border-info mt-3 px-4 lg" novalidate>
          {{ form.hidden_tag() }}
          <fieldset class="d-flex flex-column">
            <center class="fs-2">Log In</center>
            <div class="form-group">
              {{ form.email.label(class='form-label') }}
              {% if form.email.errors %}
                {{ form.email(class='form-control is-invalid') }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class='form-control') }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.password.label(class='form-label') }}
              {% if form.password.errors %}
                {{ form.password(class='form-control is-invalid') }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.password(class='form-control') }}
              {% endif %}
            </div>
            <div class="form-check">
              {{form.remember.label(class="form-check-label")}}
              {{form.remember(class="form-check-input")}}
            </div>          
          </fieldset>
          <div class="form-group text-center">{{ form.submit(class='btn btn-primary my-3') }}</div>
          <div class="text-center">
            <small>New Here? <a class="" href="{{ url_for('users.register') }}"> Register</a></small>
            <small class="text-muted px-2"><a class="" href="{{url_for("users.request_password")}}">Forgot Password?</a></small>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

package/templates/post.html
{% extends 'layouts.html' %}
{% block content %}
<div class="bg-light rounded text-black my-4 mx-3">
  <div class="container d-flex py-3 justify-content-center my-3 flex-md-row flex-column">
    <div class="d-flex align-items-center justify-content-center">
      <img class="rounded-circle" src="{{ url_for('static', filename='profile_pics/' + post.author.image) }}" style="width: 100px;  height: 100px;" />
    </div>
    <div class="flex-fill text-center mx-3 py-3">
      <p class="title fs-4 text-decoration-none text-black">{{ post.title }}</p>

      <p class="mt-3">{{ post.content }}</p>
    </div>
    <div class="d-flex flex-column pt-3" style="min-width: 155px;">
      {% if current_user.username == post.author.username %}
        <div class="my-2 d-flex justify-content-center">
          <a class="btn btn-info me-1" href="{{ url_for('posts.update_post', id=post.id) }}">Update</a>
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">Delete</button>
        </div>
      {% endif %}
      <div class="d-flex flex-md-column justify-content-center flex-wrap">
        <p class="bold fw-4 fs-5 m-0">Published By</p>
        <a href="{{url_for("users.user_post", username=post.author.username)}}" class="text-decoration-none mx-1 pt-1">{{ post.author.username }}</a>
        <p class="m-0 pt-1 mx-1">on</p>
        <p class="pt-1 m-0">{{ post.date_posted.strftime('%d %B %Y') }}</p>
      </div>
    </div>
  </div>
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header text-black">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Post</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-black">Are you Sure you want to delete this post. It cannot be restored again</div>
        <div class="modal-footer">
          <form action="{{ url_for('posts.delete_post', id=post.id) }}" method="post">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-around bg-info">
    <form method="post" action="{{url_for("posts.like_post", id=post.id)}}">
      {% if current_user.is_authenticated and post.has_liked(current_user)%}
      <button id="like" type="submit" class="bg-info border-0 text-primary pb-2 d-flex"><p class="pe-2 pt-1 m-0 fw-semibold">Like</p><img src="{{url_for("static", filename="icons/image2.png")}}" class="mt-2 me-1"  style="width: 15px; height: 15px;"></img><p class="pt-1 my-0 fw-semibold"> ({{like_post}})</p></button>
      {%  else %}
      <button  id="like" type="submit" class="bg-info border-0 text-primary pb-2 d-flex"><p class="pe-2 pt-1 m-0 fw-semibold">Like</p><img src="{{url_for("static", filename="icons/image.png")}}"  class="mt-2 me-1" style="width: 15px; height: 15px;"></img><p class="pt-1 my-0 fw-semibold"> ({{like_post}})</p></button>
      {% endif %}
    </form>
    <a href="{{url_for("comment.new_comment", p_id=post.id)}}" class="text-decoration-none pt-1">Comment 💬</a>
  </div>
</div>
{% endblock %}

package/templates/request_password.html
{% extends 'layouts.html' %}
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="POST" action="" class="border border-info mt-3 px-4 lg" novalidate>
          {{ form.hidden_tag() }}
          <fieldset class="d-flex flex-column">
            <center class="fs-2">Reset password</center>
            <div class="form-group">
              {{ form.email.label(class='form-label') }}
              {% if form.email.errors %}
                {{ form.email(class='form-control is-invalid') }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class='form-control') }}
              {% endif %}
            </div>         
          </fieldset>
          <div class="form-group text-center">{{ form.submit(class='btn btn-primary my-3') }}</div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

package/templates/user_posts.html
{% extends 'layouts.html' %}
{% block content %}
  <div class="col d-flex justify-content-start shadow-lg">
    <img src="{{url_for("static" , filename="profile_pics/"+user.image) }}" class="p-md-3" style="width: 300px;  height: 300px;" />
    <div class="pt-3 px-4">  
      <h4>{{user.username}}</h4>
      <h4>Total posts: {{posts.total}}</h4>
      <h4>Comments sent: {{len}}</h4>  
      <h4>Total likes received: {{likes}}</h4>  
    </div>

  </div>
  <h2 class="text-center">Posts by {{ user.username }} ({{ posts.total }})</h2>
  {% for post in posts.items %}
    <div class="bg-light rounded text-black my-4 mx-3">
      <div class="container d-flex py-3 justify-content-center my-3 flex-md-row flex-column">

        <div class="flex-fill text-center mx-3 py-3">
          <a class="title fs-4 text-decoration-none text-black" href="{{ url_for('posts.post', id=post.id) }}">{{ post.title }}</a>

          <p class="mt-3">{{ post.content }}</p>
        </div>
        <div class="d-flex flex-md-column justify-content-center flex-wrap">
          <p class="bold fw-4 fs-5 m-0">Published By</p>
          <a href="{{ url_for('users.user_post', username=post.author.username) }}" class="text-decoration-none mx-1 pt-1">{{ post.author.username }}</a>
          <p class="m-0 pt-1 mx-1">on</p>
          <p class="pt-1 m-0">{{ post.date_posted.strftime('%d %B %Y') }}</p>
        </div>
      </div>
      <div class="d-flex justify-content-center bg-info">
        <a href="{{ url_for('comment.new_comment', p_id=post.id) }}" class="text-decoration-none">Comment 💬</a>
      </div>
    </div>
  {% endfor %}

  <div class="d-flex justify-content-center">
    {% for page in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page %}
        {% if posts.page == page %}
          <a href="{{ url_for('users.user_post', page=page, username=user.username) }}" class="btn btn-info border boder-1 mx-1">{{ page }}</a>
        {% else %}
          <a href="{{ url_for('users.user_post', page=page, username=user.username) }}" class="btn btn-light border boder-1 mx-1">{{ page }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
{% endblock %}